example:
  properties: I AM THE DEFAULT

spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1

management:
  endpoints:
    enabled-by-default: true