spring:
  application:
    name: config-server
  profiles:
    active: vault
  cloud:
    config:
      server:
#        vault:
#          port: 8200
#          host: 127.0.0.1
#          kv-version: 2
#          backend: licensing-service
# Vault 와 Spring Actuator 함께 사용할시 에러가 발생.
# 현재 actuator 최신버전에서 발생한 이슈로 보인다. 일단 actuator 제거하고 실습시 정상 동작하는 것을 확인하였다.
# https://github.com/spring-cloud/spring-cloud-config/issues/2085
        native:
          search-locations: classpath:/config
        git:
#          스프링 클라우드 컨피그에 깃 서버와 레포지토리 경로를 알림
          uri: https://github.com/co9514/config.git
#          스프링 클라우드 컨피그에 구성파일을 찾는데 사용될 깃 경로
          search-paths: licensingservice
#          private repository 에 접근하기 위한 방법 블로그 링크 https://oingdaddy.tistory.com/188


server:
  port: 8071